version: "3.8"

services:
  proxy:
    image: steveltn/https-portal:1
    logging:
      driver: json-file
    # 所属ネットワーク
    network_mode: host
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock/:/tmp/docker.sock/:ro
    environment:
      STAGE: "${STAGE:-local}" # 本番環境の場合は production を指定（実際の Let's Encrypt に SSL 申請を行う）
      DOMAINS: "$DOMAINS" # 'domain -> http://port-forward, ...'
